In [25]:
import numpy as np
import global_params
import base_functions

# **Input image**

In [26]:
# Input image
input_image = np.array([[27280, 22946,   891, 23091, 16030,  5508],
                        [ 6261,  6394, 10538, 14803, 12960, 17081],
                        [14742, 29306, 24367,   245, 15146, 23452],
                        [ 9746, 15431, 12523, 15067, 23362,  5507],
                        [  146, 17322, 24497, 25540, 11464,  5865],
                        [24361, 10439, 19654, 21372, 25546, 28790]])

In [27]:
# Flatten input image
input_image_flatten = np.copy(input_image.flatten())

In [28]:
# Mark iterated element: If mark_iter[i] == 0, this means input_image_flatten[i] has been iterated
mark_iter = np.zeros((global_params.max_size,), dtype=np.uint8)

In [29]:
# Strobe: If strobe[i] == 1, this means in this time, input_image_flatten[i] is meaningful
# Ex: when we consider element 0, strobe[0] == 1, strobe[1] == 1, strobe[size_input_y] == 1, strobe[size_input_y + 1] == 1
# This means, in this time, we need to compare four elements togeter: input_image_flatten[0]
#                                                                     input_image_flatten[1]
#                                                                     input_image_flatten[size_input_y]
#                                                                     input_image_flatten[size_input_y + 1]
strobe = np.zeros((global_params.max_size,), dtype=np.uint8)

strobe = base_functions.update_strobe(last_iter = -1    ,
                                      strobe    = strobe )

In [30]:
# Extend index list: Extend_idx return the index where we need to extend region (list)
extend_idx = []

# **Output Matrix**

In [31]:
# Create output matrix
output = np.ones_like(input_image_flatten)

# **Regional Maxima Algorithm**

In [32]:
print("---------------------------------------------------------")
print("\t\t\t Initial Parameters")
print("---------------------------------------------------------")

print("\n1. input_image: \n", input_image)
print("\n2. input_image_flatten: \n", input_image_flatten)
print("\n3. mark_iter: \n", mark_iter)
strobe_reshape = np.reshape(np.copy(strobe), (global_params.size_input_x, global_params.size_input_y))
print("\n4. strobe: \n", strobe_reshape)
output_reshape = np.copy(output.reshape((global_params.size_input_x, global_params.size_input_y)))
print("\n5. output: \n", output_reshape)

print("\n===================================================================")

for i in range(global_params.max_size):
    str = "-" if i < 10 else ""
    print("\n\t---------------------------------------------------------")
    print("\t-------------------|      STEP ",i,"   |------------------", str)
    print("\t---------------------------------------------------------\n")
    print("\n1. Input image: \n", input_image)
    strobe_reshape = np.reshape(np.copy(strobe), (global_params.size_input_x, global_params.size_input_y))
    print("\n2. Strobe: \n", strobe_reshape)
    mark_iter_reshape = np.reshape(np.copy(mark_iter), (global_params.size_input_x, global_params.size_input_y))
    print("\n3. mark_iter: \n", mark_iter_reshape)
    print ()
    
    if (mark_iter[i] == 0):
        extend, extend_idx, reg_max, mark_iter = base_functions.compare(iter                = i                  ,
                                                                        input_image_flatten = input_image_flatten,
                                                                        strobe              = strobe             ,
                                                                        last_extend_idx     = extend_idx         ,
                                                                        mark_iter           = mark_iter           )
        while (extend):
            strobe = base_functions.update_strobe_extend(strobe     = strobe    ,
                                                         extend_idx = extend_idx )
            strobe_reshape = np.reshape(np.copy(strobe), (global_params.size_input_x, global_params.size_input_y))
            print("\n2 strobe: \n", strobe_reshape)
            extend, extend_idx, reg_max, mark_iter = base_functions.compare(iter                = i                  ,
                                                                            input_image_flatten = input_image_flatten,
                                                                            strobe              = strobe             ,
                                                                            last_extend_idx     = extend_idx         ,
                                                                            mark_iter           = mark_iter           )

        for j in range(len(extend_idx)):
            output[extend_idx[j]] = int(reg_max)
        output[i] = int(reg_max)
    
    extend_idx = []
    mark_iter[i] = 1
    
    strobe =  base_functions.update_strobe(last_iter = i     ,
                                           strobe    = strobe )
    output_reshape = np.reshape(np.copy(output), (global_params.size_input_x, global_params.size_input_y))
    print("\n4. New output: \n", output_reshape)
            

---------------------------------------------------------
			 Initial Parameters
---------------------------------------------------------

1. input_image: 
 [[27280 22946   891 23091 16030  5508]
 [ 6261  6394 10538 14803 12960 17081]
 [14742 29306 24367   245 15146 23452]
 [ 9746 15431 12523 15067 23362  5507]
 [  146 17322 24497 25540 11464  5865]
 [24361 10439 19654 21372 25546 28790]]

2. input_image_flatten: 
 [27280 22946   891 23091 16030  5508  6261  6394 10538 14803 12960 17081
 14742 29306 24367   245 15146 23452  9746 15431 12523 15067 23362  5507
   146 17322 24497 25540 11464  5865 24361 10439 19654 21372 25546 28790]

3. mark_iter: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

4. strobe: 
 [[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

5. output: 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


	--------------------------------------------------------